### ISSUE TITLE
[p2p Code Review] Suggestions for improvement

### ISSUE THREAD

**Issue by gvgesanto2** [indigodavid/leaderboard#3]
## Hi @indigodavid 👋,

Your code is top-notch, congrats!

## To Highlight 💯 
- **About the UI:**
✔️ Good UI Design
✔️ Good UI/UX experience showing up status messages to the user when a new score is added
- **About the code:**
✔️ Clean and descriptive code
✔️ Well-organized code (good job creating a module for each function of your application)
✔️ Good job creating functions responsible to deal with the DOM manipulation tasks and others responsible to deal with the API logic. In this way, you kept your app business logic separated from your presentation logic by applying the [SoC principle (Separation of concerns principle)](https://en.wikipedia.org/wiki/Separation_of_concerns)!

## Suggestions
- As pointed out in the highlights, your code is very well-organized. You have a file for each function, which is excellent! But as your app grows, you might have some organization problems if all your files are inside the same folder. **So, the next step is to try to think of some folder structure to organize your files.** 
I've downloaded your code and created a Github repository with an example of how you could have organized your files (I basically just separated the files responsible to deal with the DOM from the files responsible to deal with the API): https://github.com/gvgesanto2/leaderboard-david-example
However, there's no right answer for this one, you could organize your files by responsibility (concern), by domain, by entity, by feature, etc. The best option is the option that suits you, your team, and your project needs the best!

**Comment by indigodavid** [comment]
Hi @gvgesanto2, 

Thanks for your recommendation. I followed the file structure you posted, and I'm quite happy about it. The latest implementation follows that structure. Best regards!
